twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      teleop:
        topic   : /teleop/cmd_vel
        timeout : 0.5
        priority: 10
      navigation:
        topic   : /nav/cmd_vel
        timeout : 0.5
        priority: 5
